// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test1;

import java.util.*;
import org.openlegacy.rpc.RpcEntity;

privileged @SuppressWarnings("unused") aspect Itemdetail_Aspect {
    declare parents: Itemdetail implements RpcEntity;
    
    public Integer Itemdetail.getItemNum(){
    	return this.itemNum;
    }
    public void Itemdetail.setItemNum(Integer itemNum){
    	this.itemNum = itemNum;
    }
    public ItemRecord Itemdetail.getItemRecord(){
    	return this.itemRecord;
    }
    public void Itemdetail.setItemRecord(ItemRecord itemRecord){
    	this.itemRecord = itemRecord;
    }
    public Shipping Itemdetail.getShipping(){
    	return this.shipping;
    }
    public void Itemdetail.setShipping(Shipping shipping){
    	this.shipping = shipping;
    }
    
}
