// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test1;

import java.util.*;
import com.test1.Itemdetail.*;

privileged @SuppressWarnings("unused") aspect Shipping_Aspect {
    
    public String Shipping.getShippingMethod(){
    	return this.shippingMethod;
    }
    public void Shipping.setShippingMethod(String shippingMethod){
    	this.shippingMethod = shippingMethod;
    }
    public Integer Shipping.getDays(){
    	return this.days;
    }
    public void Shipping.setDays(Integer days){
    	this.days = days;
    }
    
}
