// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.position.screens;

import java.util.*;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.Color;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

privileged @SuppressWarnings("unused") aspect PositionDrillDownMenu_Aspect {

    declare parents: PositionDrillDownMenu implements ScreenEntity;
    private String PositionDrillDownMenu.focusField;
    private List<TerminalActionDefinition> PositionDrillDownMenu.actions = new ArrayList<TerminalActionDefinition>();
    
	

	

    private List<TerminalActionDefinition> PositionDrillDownMenu.displayTheLoadallSubfileRecordsActions = new ArrayList<TerminalActionDefinition>();
    

    public String PositionDrillDownMenu.getRrn(){
    	return this.rrn;
    }
    

    public List<DisplayTheLoadallSubfileRecord> PositionDrillDownMenu.getDisplayTheLoadallSubfileRecords(){
    	return this.displayTheLoadallSubfileRecords;
    }
    

    public List<TerminalActionDefinition> PositionDrillDownMenu.getDisplayTheLoadallSubfileRecordsActions(){
    	return this.displayTheLoadallSubfileRecordsActions;
    }

    public String PositionDrillDownMenu.getFocusField(){
    	return focusField;
    }
    public void PositionDrillDownMenu.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> PositionDrillDownMenu.getActions(){
    	return actions;
    }
    
}
