// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.position.screens;

import java.util.*;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.Color;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

privileged @SuppressWarnings("unused") aspect PositionDrillDownDetail_Aspect {

    declare parents: PositionDrillDownDetail implements ScreenEntity;
    private String PositionDrillDownDetail.focusField;
    private List<TerminalActionDefinition> PositionDrillDownDetail.actions = new ArrayList<TerminalActionDefinition>();
    
	

    

    public String PositionDrillDownDetail.getRrn(){
    	return this.rrn;
    }
    


    public String PositionDrillDownDetail.getFocusField(){
    	return focusField;
    }
    public void PositionDrillDownDetail.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> PositionDrillDownDetail.getActions(){
    	return actions;
    }
    
}
