// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test1;

import java.util.*;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.Color;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

privileged @SuppressWarnings("unused") aspect ItemDetails_Aspect {

    declare parents: ItemDetails implements ScreenEntity;
    private String ItemDetails.focusField;
    private List<TerminalActionDefinition> ItemDetails.actions = new ArrayList<TerminalActionDefinition>();
    
	

	

	

	

	

	

	

	

	

    

    public Integer ItemDetails.getItemNumber(){
    	return this.itemNumber;
    }
    
    public void ItemDetails.setItemNumber(Integer itemNumber){
    	this.itemNumber = itemNumber;
    }



    public String ItemDetails.getItemDescription(){
    	return this.itemDescription;
    }
    
    public void ItemDetails.setItemDescription(String itemDescription){
    	this.itemDescription = itemDescription;
    }



    public String ItemDetails.getSubstituteItemNumber(){
    	return this.substituteItemNumber;
    }
    
    public void ItemDetails.setSubstituteItemNumber(String substituteItemNumber){
    	this.substituteItemNumber = substituteItemNumber;
    }



    public Integer ItemDetails.getItemWeight(){
    	return this.itemWeight;
    }
    
    public void ItemDetails.setItemWeight(Integer itemWeight){
    	this.itemWeight = itemWeight;
    }



    public StockGroup ItemDetails.getStockGroup(){
    	return this.stockGroup;
    }
    
    public void ItemDetails.setStockGroup(StockGroup stockGroup){
    	this.stockGroup = stockGroup;
    }



    public String ItemDetails.getUnitOfMeasure(){
    	return this.unitOfMeasure;
    }
    
    public void ItemDetails.setUnitOfMeasure(String unitOfMeasure){
    	this.unitOfMeasure = unitOfMeasure;
    }



    public String ItemDetails.getPalletLabelRequired(){
    	return this.palletLabelRequired;
    }
    
    public void ItemDetails.setPalletLabelRequired(String palletLabelRequired){
    	this.palletLabelRequired = palletLabelRequired;
    }



    public String ItemDetails.getVatCode(){
    	return this.vatCode;
    }
    
    public void ItemDetails.setVatCode(String vatCode){
    	this.vatCode = vatCode;
    }



    public StockDetails ItemDetails.getStockDetails(){
    	return this.stockDetails;
    }
    




    public String ItemDetails.getFocusField(){
    	return focusField;
    }
    public void ItemDetails.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> ItemDetails.getActions(){
    	return actions;
    }
    
}
