// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test1;

import java.util.*;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.Color;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

privileged @SuppressWarnings("unused") aspect MainMenu_Aspect {

    declare parents: MainMenu implements ScreenEntity;
    private String MainMenu.focusField;
    private List<TerminalActionDefinition> MainMenu.actions = new ArrayList<TerminalActionDefinition>();
    
	

    

    public Integer MainMenu.getMenuSelection(){
    	return this.menuSelection;
    }
    
    public void MainMenu.setMenuSelection(Integer menuSelection){
    	this.menuSelection = menuSelection;
    }




    public String MainMenu.getFocusField(){
    	return focusField;
    }
    public void MainMenu.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> MainMenu.getActions(){
    	return actions;
    }
    
}
