// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.someorg.examples.screens;

import org.openlegacy.terminal.ScreenPosition;
import org.openlegacy.terminal.TerminalField;
import org.openlegacy.terminal.TerminalScreen;
import org.openlegacy.terminal.CursorContainer;
import org.springframework.stereotype.Component;

privileged aspect InventoryManagement_Aspect {
    
    declare @type: InventoryManagement : @Component;
    
    private TerminalScreen InventoryManagement.terminalScreen;

    declare parents: InventoryManagement implements CursorContainer;

    private ScreenPosition InventoryManagement.cursorPosition;
    
    private TerminalField InventoryManagement.SelectionField;
    
    public TerminalScreen InventoryManagement.getTerminalScreen(){
		return terminalScreen;
    }

    public String InventoryManagement.getSelection(){
    	return this.Selection;
    }
    
    public void InventoryManagement.setSelection(String Selection){
    	this.Selection = Selection;
    }

    public TerminalField InventoryManagement.getSelectionField(){
    	return SelectionField;
    }

    public ScreenPosition InventoryManagement.getCursorPosition(){
    	return cursorPosition;
    }
    public void InventoryManagement.setCursorPosition(ScreenPosition cursorPosition){
    	this.cursorPosition = cursorPosition;
    }
    
}
