// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.someorg.examples.screens;

import org.openlegacy.terminal.ScreenEntity;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged aspect ItemDetails2_Aspect {
    
    declare @type: ItemDetails2 : @Component;
	declare @type: ItemDetails2 : @Scope("prototype");
    

    declare parents: ItemDetails2 implements ScreenEntity;
    
	
    

    public String ItemDetails2.getItemNumber(){
    	return this.ItemNumber;
    }
    


    
}
