// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.someorg.examples.screens;

import org.openlegacy.terminal.ScreenPosition;
import org.openlegacy.terminal.TerminalField;
import org.openlegacy.terminal.TerminalScreen;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.CursorContainer;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged aspect ItemDetails2_Aspect {
    
    declare parents: ItemDetails2 implements ScreenEntity;
    declare parents: ItemDetails2 implements CursorContainer;

	declare @type: ItemDetails2 : @Component;
	declare @type: ItemDetails2 : @Scope("prototype");
    
    private TerminalScreen ItemDetails2.terminalScreen;

    private ScreenPosition ItemDetails2.cursorPosition;
    
    private TerminalField ItemDetails2.ItemNumberField;
    
    public TerminalScreen ItemDetails2.getTerminalScreen(){
		return terminalScreen;
    }

    public String ItemDetails2.getItemNumber(){
    	return this.ItemNumber;
    }
    
    public void ItemDetails2.setItemNumber(String ItemNumber){
    	this.ItemNumber = ItemNumber;
    }

    public TerminalField ItemDetails2.getItemNumberField(){
    	return ItemNumberField;
    }

    public ScreenPosition ItemDetails2.getCursorPosition(){
    	return cursorPosition;
    }
    public void ItemDetails2.setCursorPosition(ScreenPosition cursorPosition){
    	this.cursorPosition = cursorPosition;
    }
    
}
