// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.someorg.examples.screens;

import org.openlegacy.terminal.ScreenPosition;
import org.openlegacy.terminal.TerminalField;
import org.openlegacy.terminal.TerminalScreen;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.CursorContainer;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged aspect MainMenu_Aspect {
    
    declare parents: MainMenu implements ScreenEntity;
    declare parents: MainMenu implements CursorContainer;

	declare @type: MainMenu : @Component;
	declare @type: MainMenu : @Scope("prototype");
    
    private TerminalScreen MainMenu.terminalScreen;


    private ScreenPosition MainMenu.cursorPosition;
    
    private TerminalField MainMenu.companyField;
    private TerminalField MainMenu.selectionField;
    
    public TerminalScreen MainMenu.getTerminalScreen(){
		return terminalScreen;
    }

    public String MainMenu.getCompany(){
    	return this.company;
    }
    
    public void MainMenu.setCompany(String company){
    	this.company = company;
    }

    public TerminalField MainMenu.getCompanyField(){
    	return companyField;
    }
    public String MainMenu.getSelection(){
    	return this.selection;
    }
    
    public void MainMenu.setSelection(String selection){
    	this.selection = selection;
    }

    public TerminalField MainMenu.getSelectionField(){
    	return selectionField;
    }

    public ScreenPosition MainMenu.getCursorPosition(){
    	return cursorPosition;
    }
    public void MainMenu.setCursorPosition(ScreenPosition cursorPosition){
    	this.cursorPosition = cursorPosition;
    }
    
}
