// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import org.openlegacy.terminal.TerminalField;

privileged @SuppressWarnings("unused") aspect AbstractScreen_Aspect {

    
	
    private TerminalField AbstractScreen.errorField;

    

    public String AbstractScreen.getError(){
    	return this.error;
    }
    public TerminalField AbstractScreen.getErrorField(){
    	return this.errorField;
    }
    




    
}
