// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.*;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

privileged @SuppressWarnings("unused") aspect InventoryManagement_Aspect {

    declare parents: InventoryManagement implements ScreenEntity;
    private String InventoryManagement.focusField;
    private List<TerminalActionDefinition> InventoryManagement.actions = new ArrayList<TerminalActionDefinition>();
    
	

    

    public String InventoryManagement.getSelection(){
    	return this.selection;
    }
    
    public void InventoryManagement.setSelection(String selection){
    	this.selection = selection;
    }




    public String InventoryManagement.getFocusField(){
    	return focusField;
    }
    public void InventoryManagement.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> InventoryManagement.getActions(){
    	return actions;
    }
    
}
