// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.List;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import apps.inventory.screens.ItemsList.ItemsListRow;

privileged @SuppressWarnings("unused") aspect ItemsListRow_Aspect {

	
    
    private String ItemsListRow.focusField;
	
    public String ItemsListRow.getAction(){
    	return this.action;
    }
    
    public void ItemsListRow.setAction(String action){
    	this.action = action;
    }

    public Integer ItemsListRow.getItemNumber(){
    	return this.itemNumber;
    }
    

    public String ItemsListRow.getAlphaSearch(){
    	return this.alphaSearch;
    }
    

    public String ItemsListRow.getItemDescription(){
    	return this.itemDescription;
    }
    

    public String ItemsListRow.getItemCategory(){
    	return this.itemCategory;
    }
    


    /**
    	Focus on the given field, or on the first field in the table if none is given
    */
    public void ItemsListRow.focus(String... field) {
        if (field.length > 0) {
            this.focusField = field[0];
        } else {
            this.focusField = "action";
        }
    }

    public String ItemsListRow.getFocus() {
        return focusField;
    }
    public void ItemsListRow.setFocus(String focus) {
        this.focusField = focus;
    }
		
    public int ItemsListRow.hashCode(){
		return HashCodeBuilder.reflectionHashCode(this);
    }

    public boolean ItemsListRow.equals(Object other){
    	// TODO exclude terminal fields
		return EqualsBuilder.reflectionEquals(this,other);
    }
}