// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.List;
import org.openlegacy.terminal.ScreenEntity;

privileged @SuppressWarnings("unused") aspect ItemDetails1_Aspect {
    
    declare parents: ItemDetails1 implements ScreenEntity;
    private String ItemDetails1.focusField;
    
	
	
	
	
    

    public String ItemDetails1.getItemDescription(){
    	return this.itemDescription;
    }
    
    public void ItemDetails1.setItemDescription(String itemDescription){
    	this.itemDescription = itemDescription;
    }

    public ItemDetails2 ItemDetails1.getItemDetails2(){
    	return this.itemDetails2;
    }
    

    public Integer ItemDetails1.getItemNumber(){
    	return this.itemNumber;
    }
    

    public Boolean ItemDetails1.getPalletLabelRequired(){
    	return this.palletLabelRequired;
    }
    
    public void ItemDetails1.setPalletLabelRequired(Boolean palletLabelRequired){
    	this.palletLabelRequired = palletLabelRequired;
    }


    public String ItemDetails1.getFocusField(){
    	return focusField;
    }
    public void ItemDetails1.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
}
