// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.*;
import org.openlegacy.terminal.TerminalField;
import apps.inventory.screens.ItemDetails2.AuditDetails;

privileged @SuppressWarnings("unused") aspect AuditDetailsPart_Aspect {
    private TerminalField AuditDetails.createdDateField;
    private TerminalField AuditDetails.createdByField;
    
    public String AuditDetails.getCreatedDate(){
    	return this.createdDate;
    }
    

    public TerminalField AuditDetails.getCreatedDateField(){
    	return createdDateField;
    }
		
    public String AuditDetails.getCreatedBy(){
    	return this.createdBy;
    }
    

    public TerminalField AuditDetails.getCreatedByField(){
    	return createdByField;
    }
		
}
