// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.*;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

privileged @SuppressWarnings("unused") aspect ItemDetails1_Aspect {

    declare parents: ItemDetails1 implements ScreenEntity;
    private String ItemDetails1.focusField;
    private List<TerminalActionDefinition> ItemDetails1.actions = new ArrayList<TerminalActionDefinition>();
    
	

	

	

	

	

	

    private String ItemDetails1.itemClassDescription;
	

    private String ItemDetails1.stockGroupDescription;
	

	

	

	

    

    public Integer ItemDetails1.getItemNumber(){
    	return this.itemNumber;
    }
    



    public String ItemDetails1.getItemDescription(){
    	return this.itemDescription;
    }
    
    public void ItemDetails1.setItemDescription(String itemDescription){
    	this.itemDescription = itemDescription;
    }



    public String ItemDetails1.getSupercedingItemTo(){
    	return this.supercedingItemTo;
    }
    
    public void ItemDetails1.setSupercedingItemTo(String supercedingItemTo){
    	this.supercedingItemTo = supercedingItemTo;
    }



    public String ItemDetails1.getSupercedingItemFrom(){
    	return this.supercedingItemFrom;
    }
    
    public void ItemDetails1.setSupercedingItemFrom(String supercedingItemFrom){
    	this.supercedingItemFrom = supercedingItemFrom;
    }



    public Long ItemDetails1.getItemWeight(){
    	return this.itemWeight;
    }
    
    public void ItemDetails1.setItemWeight(Long itemWeight){
    	this.itemWeight = itemWeight;
    }



    public String ItemDetails1.getItemClass(){
    	return this.itemClass;
    }
    
    public void ItemDetails1.setItemClass(String itemClass){
    	this.itemClass = itemClass;
    }

    public String  ItemDetails1.getItemClassDescription(){
    	return this.itemClassDescription;
    }


    public String ItemDetails1.getStockGroup(){
    	return this.stockGroup;
    }
    
    public void ItemDetails1.setStockGroup(String stockGroup){
    	this.stockGroup = stockGroup;
    }

    public String  ItemDetails1.getStockGroupDescription(){
    	return this.stockGroupDescription;
    }


    public Integer ItemDetails1.getPackagingMultipler(){
    	return this.packagingMultipler;
    }
    
    public void ItemDetails1.setPackagingMultipler(Integer packagingMultipler){
    	this.packagingMultipler = packagingMultipler;
    }



    public Boolean ItemDetails1.getPalletLabelRequired(){
    	return this.palletLabelRequired;
    }
    
    public void ItemDetails1.setPalletLabelRequired(Boolean palletLabelRequired){
    	this.palletLabelRequired = palletLabelRequired;
    }



    public OuterUnitOfMeasure ItemDetails1.getOuterUnitOfMeasure(){
    	return this.outerUnitOfMeasure;
    }
    
    public void ItemDetails1.setOuterUnitOfMeasure(OuterUnitOfMeasure outerUnitOfMeasure){
    	this.outerUnitOfMeasure = outerUnitOfMeasure;
    }



    public ItemDetails2 ItemDetails1.getItemDetails2(){
    	return this.itemDetails2;
    }
    




    public String ItemDetails1.getFocusField(){
    	return focusField;
    }
    public void ItemDetails1.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> ItemDetails1.getActions(){
    	return actions;
    }
    
}
