// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.List;
import org.openlegacy.terminal.ScreenEntity;

privileged aspect ItemsList_Aspect {
    
    declare parents: ItemsList implements ScreenEntity;
    private String ItemsList.focusField;
    
	
	
	
    

    public String ItemsList.getErrorMessage(){
    	return this.errorMessage;
    }
    

    public List<ItemsListRow> ItemsList.getItemListRows(){
    	return this.itemListRows;
    }
    

    public String ItemsList.getPositionTo(){
    	return this.positionTo;
    }
    


    public String ItemsList.getFocusField(){
    	return focusField;
    }
    public void ItemsList.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
}
