// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

import java.util.ArrayList;
import java.util.List;

privileged @SuppressWarnings("unused") aspect MainMenu_Aspect {

    declare parents: MainMenu implements ScreenEntity;
    private String MainMenu.focusField;
    private List<TerminalActionDefinition> MainMenu.actions = new ArrayList<TerminalActionDefinition>();
    
	

	

    

    public Integer MainMenu.getCompany(){
    	return this.company;
    }
    
    public void MainMenu.setCompany(Integer company){
    	this.company = company;
    }



    public Integer MainMenu.getSelection(){
    	return this.selection;
    }
    
    public void MainMenu.setSelection(Integer selection){
    	this.selection = selection;
    }




    public String MainMenu.getFocusField(){
    	return focusField;
    }
    public void MainMenu.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> MainMenu.getActions(){
    	return actions;
    }
    
}
