// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.*;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

privileged @SuppressWarnings("unused") aspect WarehousesList_Aspect {

    declare parents: WarehousesList implements ScreenEntity;
    private String WarehousesList.focusField;
    private List<TerminalActionDefinition> WarehousesList.actions = new ArrayList<TerminalActionDefinition>();
    
	

    

    public List<WarehousesListRow> WarehousesList.getWarehousesListRows(){
    	return this.warehousesListRows;
    }
    




    public String WarehousesList.getFocusField(){
    	return focusField;
    }
    public void WarehousesList.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> WarehousesList.getActions(){
    	return actions;
    }
    
}
