// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.*;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

privileged @SuppressWarnings("unused") aspect WarehouseDetails_Aspect {

    declare parents: WarehouseDetails implements ScreenEntity;
    private String WarehouseDetails.focusField;
    private List<TerminalActionDefinition> WarehouseDetails.actions = new ArrayList<TerminalActionDefinition>();
    
	

	

	

	

	

	

	

	

	

    private Map<Object,Object> WarehouseDetails.warehouseTypeValues;
    

    public Integer WarehouseDetails.getWarehouseNumber(){
    	return this.warehouseNumber;
    }
    



    public String WarehouseDetails.getWarehouseDescription(){
    	return this.warehouseDescription;
    }
    
    public void WarehouseDetails.setWarehouseDescription(String warehouseDescription){
    	this.warehouseDescription = warehouseDescription;
    }



    public Integer WarehouseDetails.getCostingType(){
    	return this.costingType;
    }
    
    public void WarehouseDetails.setCostingType(Integer costingType){
    	this.costingType = costingType;
    }



    public String WarehouseDetails.getAddress(){
    	return this.address;
    }
    
    public void WarehouseDetails.setAddress(String address){
    	this.address = address;
    }



    public String WarehouseDetails.getPhone(){
    	return this.phone;
    }
    
    public void WarehouseDetails.setPhone(String phone){
    	this.phone = phone;
    }



    public String WarehouseDetails.getEmail(){
    	return this.email;
    }
    
    public void WarehouseDetails.setEmail(String email){
    	this.email = email;
    }



    public String WarehouseDetails.getAmendedBy(){
    	return this.amendedBy;
    }
    
    public void WarehouseDetails.setAmendedBy(String amendedBy){
    	this.amendedBy = amendedBy;
    }



    public String WarehouseDetails.getCreatedBy(){
    	return this.createdBy;
    }
    
    public void WarehouseDetails.setCreatedBy(String createdBy){
    	this.createdBy = createdBy;
    }



    public String WarehouseDetails.getWarehouseType(){
    	return this.warehouseType;
    }
    
    public void WarehouseDetails.setWarehouseType(String warehouseType){
    	this.warehouseType = warehouseType;
    }

    public Map<Object,Object> WarehouseDetails.getWarehouseTypeValues(){
    	return warehouseTypeValues;
    }



    public String WarehouseDetails.getFocusField(){
    	return focusField;
    }
    public void WarehouseDetails.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> WarehouseDetails.getActions(){
    	return actions;
    }
    
}
