// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.List;
import java.util.Map;

import org.openlegacy.terminal.ScreenEntity;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged @SuppressWarnings("unused") aspect WarehouseDetails_Aspect {
    
    declare @type: WarehouseDetails : @Component;
	declare @type: WarehouseDetails : @Scope("prototype");
    

    declare parents: WarehouseDetails implements ScreenEntity;
    private String WarehouseDetails.focusField;
    
    private Map<Object,Object> WarehouseDetails.warehouseTypeValues;
    
	
	
    

    public String WarehouseDetails.getWarehouseNumber(){
    	return this.warehouseNumber;
    }
    

    public String WarehouseDetails.getWarehouseType(){
    	return this.warehouseType;
    }

    public Map<Object,Object> WarehouseDetails.getWarehouseTypeValues(){
    	return this.warehouseTypeValues;
    }
    
    public void WarehouseDetails.setWarehouseType(String warehouseType){
    	this.warehouseType = warehouseType;
    }


    public String WarehouseDetails.getFocusField(){
    	return focusField;
    }
    public void WarehouseDetails.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
}
