// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.List;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import apps.inventory.screens.WarehousesList.WarehousesListRow;

privileged @SuppressWarnings("unused") aspect WarehousesListRow_Aspect {

	
    
    private String WarehousesListRow.focusField;
	
    public String WarehousesListRow.getAction(){
    	return this.action;
    }
    
    public void WarehousesListRow.setAction(String action){
    	this.action = action;
    }

    public String WarehousesListRow.getWarehouseNumber(){
    	return this.warehouseNumber;
    }
    

    public String WarehousesListRow.getWarehouseDescription(){
    	return this.warehouseDescription;
    }
    


    /**
    	Focus on the given field, or on the first field in the table if none is given
    */
    public void WarehousesListRow.focus(String... field) {
        if (field.length > 0) {
            this.focusField = field[0];
        } else {
            this.focusField = "action";
        }
    }

    public String WarehousesListRow.getFocus() {
        return focusField;
    }
    public void WarehousesListRow.setFocus(String focus) {
        this.focusField = focus;
    }
		
    public int WarehousesListRow.hashCode(){
		return HashCodeBuilder.reflectionHashCode(this);
    }

    public boolean WarehousesListRow.equals(Object other){
    	// TODO exclude terminal fields
		return EqualsBuilder.reflectionEquals(this,other);
    }
}