// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.List;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import apps.inventory.screens.WarehouseTypes.WarehouseTypeRow;

privileged @SuppressWarnings("unused") aspect WarehouseTypeRow_Aspect {

	
    
    private String WarehouseTypeRow.focusField;
	
    public String WarehouseTypeRow.getAction(){
    	return this.action;
    }
    
    public void WarehouseTypeRow.setAction(String action){
    	this.action = action;
    }

    public String WarehouseTypeRow.getWarehouseType(){
    	return this.warehouseType;
    }
    

    public String WarehouseTypeRow.getWarehouseTypeDescription(){
    	return this.warehouseTypeDescription;
    }
    


    /**
    	Focus on the given field, or on the first field in the table if none is given
    */
    public void WarehouseTypeRow.focus(String... field) {
        if (field.length > 0) {
            this.focusField = field[0];
        } else {
            this.focusField = "action";
        }
    }

    public String WarehouseTypeRow.getFocus() {
        return focusField;
    }
    public void WarehouseTypeRow.setFocus(String focus) {
        this.focusField = focus;
    }
		
    public int WarehouseTypeRow.hashCode(){
		return HashCodeBuilder.reflectionHashCode(this);
    }

    public boolean WarehouseTypeRow.equals(Object other){
    	// TODO exclude terminal fields
		return EqualsBuilder.reflectionEquals(this,other);
    }
}