// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import apps.inventory.screens.WarehouseTypes.WarehouseTypeRow;

import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

import java.util.ArrayList;
import java.util.List;

privileged @SuppressWarnings("unused") aspect WarehouseTypes_Aspect {

    declare parents: WarehouseTypes implements ScreenEntity;
    private String WarehouseTypes.focusField;
    private List<TerminalActionDefinition> WarehouseTypes.actions = new ArrayList<TerminalActionDefinition>();
    
	

    

    public List<WarehouseTypeRow> WarehouseTypes.getWarehouseTypeRows(){
    	return this.warehouseTypeRows;
    }
    




    public String WarehouseTypes.getFocusField(){
    	return focusField;
    }
    public void WarehouseTypes.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> WarehouseTypes.getActions(){
    	return actions;
    }
    
}
