// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.List;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.TerminalField;
import org.openlegacy.terminal.TerminalSnapshot;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged @SuppressWarnings("unused") aspect AbstractScreen_Aspect {
    
    

    
	
    private TerminalField AbstractScreen.errorField;
    

    public String AbstractScreen.getError(){
    	return this.error;
    }
    

    public TerminalField AbstractScreen.getErrorField(){
    	return errorField;
    }

    
}
