package openlegacy;

rule "identify-readonly-fields"
ruleflow-group "identify-readonly-fields"
when
	$ruleParameterSet: RuleParametersSet(ruleId == "identify-readonly-fields")
	$labelRegex      : String()  from (String)$ruleParameterSet.getRuleParameters().get("labelRegex");
	
	// there is a screen definition
	$screenEntityDefinition: ScreenEntityDesigntimeDefinition()

	// and a snapshot
	$snapshot: TerminalSnapshot() from $screenEntityDefinition.getSnapshot()
	
	// and an field within the snapshot
	$field: TerminalField(editable == false, length > 0) from $snapshot.getFields()
	
	// with a leading label before the field which is in the format of "Field A...:"
	TerminalField(position.row == $field.position.row, position.column < $field.position.column, editable == false,value matches $labelRegex, $leadingLabel: value) from $snapshot.getFields()
then
	screenEntityDefinitionsBuilder.addField($screenEntityDefinition,$field,$leadingLabel);
end
