package openlegacy;
rule "identify-snapshots"
ruleflow-group "identify-snapshots"
when
	$ruleParameterSet: RuleParametersSet(ruleId == "identify-snapshots")
	$identifierRegex    : String()  from (String)$ruleParameterSet.getRuleParameters().get("identifierRegex");
	
	// there is a screen definition
	$screenEntityDefinition: ScreenEntityDesigntimeDefinition()
	// which has a snaphot
	$snapshot: TerminalSnapshot() from $screenEntityDefinition.snapshot

	$identifiers: List() from collect (TerminalField(value matches $identifierRegex, editable == false) from $snapshot.getFields())
then
	screenEntityDefinitionsBuilder.addIdentifiers(snapshotsAnalyzerContext,$screenEntityDefinition,$identifiers);
end