package openlegacy;

rule "find-editable-fields"
ruleflow-group "identify-editable-fields"
when
	// there is a screen definition
	$screenEntityDefinition: ScreenEntityDesigntimeDefinition()

	// and a snapshot
	$snapshot: TerminalSnapshot() from $screenEntityDefinition.getSnapshot()
	
	// and an editable field within the snapshot
	$editableField: TerminalField(editable == true) from $snapshot.getFields()
	
	// with a leading label before the editable field (same row, lower column)
	$labelField: TerminalField(position.row == $editableField.position.row, position.column < $editableField.position.column, editable == false) from $snapshot.getFields()

	// and no other field on the left of the label field 
	not TerminalField(this != $editableField,position.row == $labelField.position.row, position.column > $labelField.position.column) from $snapshot.getFields()
then
	screenEntityDefinitionsBuilder.addField($screenEntityDefinition,$editableField,$labelField.getValue());
end