package openlegacy;

rule "find-editable-fields"
ruleflow-group "identify-editable-fields"
when
	// there is a screen definition
	$screenEntityDefinition: ScreenEntityDesigntimeDefinition()

	// and a snapshot
	$snapshot: TerminalSnapshot() from $screenEntityDefinition.getSnapshot()
	
	// and an editable field within the snapshot
	$editableField: TerminalField(editable == true) from $snapshot.getFields()
	
	// with a leading label before the editable field (same row, lower column)
	TerminalField(position.row == $editableField.position.row, position.column < $editableField.position.column, editable == false,$leadingLabel: value) from $snapshot.getFields()
then
	screeEntitynDefinitionsBuilder.addField($screenEntityDefinition,$editableField,$leadingLabel);
end