package openlegacy;

rule "sort-snapshots"
ruleflow-group "initialize-screen-entities"
when
then
	// get all the snapshots provided
	Collection<TerminalSnapshot> snapshots = snapshotsAnalyzerContext.getActiveSnapshots();
	snapshotsSorter.add(snapshots);
	
	// pick 1 representer from each matched group
	snapshots = snapshotsSorter.getGroupsRepresenters();
	 
	for (TerminalSnapshot s:snapshots){
		// for snapshot, initialize an empty screen definitions container 
		ScreenEntityDesigntimeDefinition screenEntityDefinition = new SimpleScreenEntityDesigntimeDefinition();
		
		// link the definition to the snapshot
		screenEntityDefinition.setSnapshot(s);

		/// insert the definitions container to the session
		insert(screenEntityDefinition);
	} 
end
