package openlegacy;

import java.util.*;
import org.openlegacy.*;
import org.openlegacy.utils.*;
import org.openlegacy.terminal.*;
import org.openlegacy.terminal.support.*;
import org.openlegacy.terminal.definitions.*;
import org.openlegacy.analyzer.screen.model.*;
import org.openlegacy.designtime.terminal.model.support.*; 
import java.util.List;

import org.openlegacy.designtime.terminal.model.*;
import org.openlegacy.designtime.analyzer.SnapshotsSorter;
import org.openlegacy.designtime.analyzer.SnapshotsAnalyzerContext;
import org.openlegacy.designtime.analyzer.SnapshotsSimilarityChecker;
import org.openlegacy.designtime.rules.*;
import org.openlegacy.designtime.terminal.analyzer.ScreenEntityDefinitionsBuilder;

global SnapshotsAnalyzerContext snapshotsAnalyzerContext;
global SnapshotsSorter snapshotsSorter;
global ScreenEntityDefinitionsBuilder screenEntityDefinitionsBuilder;
global SnapshotsSimilarityChecker snapshotsSimilarityChecker;