// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.List;
import org.openlegacy.terminal.TerminalField;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged @SuppressWarnings("unused") aspect ItemsListItemsListRowTable_Aspect {
    
    declare @type: ItemsList.ItemsListRow : @Component;
	declare @type: ItemsList.ItemsListRow : @Scope("prototype");
    
	
    private TerminalField ItemsList.ItemsListRow.alphaSearchField;
	
    private TerminalField ItemsList.ItemsListRow.itemDescriptionField;
	
    private TerminalField ItemsList.ItemsListRow.itemNumberField;
    
    public String ItemsList.ItemsListRow.getAlphaSearch(){
    	return this.alphaSearch;
    }
    

    public TerminalField ItemsList.ItemsListRow.getAlphaSearchField(){
    	return alphaSearchField;
    }
    public String ItemsList.ItemsListRow.getItemDescription(){
    	return this.itemDescription;
    }
    

    public TerminalField ItemsList.ItemsListRow.getItemDescriptionField(){
    	return itemDescriptionField;
    }
    public String ItemsList.ItemsListRow.getItemNumber(){
    	return this.itemNumber;
    }
    

    public TerminalField ItemsList.ItemsListRow.getItemNumberField(){
    	return itemNumberField;
    }
}
