// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import java.util.List;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged @SuppressWarnings("unused") aspect ItemsListItemsListRowTable_Aspect {
    
    declare @type: ItemsList.ItemsListRow : @Component;
	declare @type: ItemsList.ItemsListRow : @Scope("prototype");
    
	
	
	
    
    public String ItemsList.ItemsListRow.getAlphaSearch(){
    	return this.alphaSearch;
    }
    

    public String ItemsList.ItemsListRow.getItemDescription(){
    	return this.itemDescription;
    }
    

    public String ItemsList.ItemsListRow.getItemNumber(){
    	return this.itemNumber;
    }
    

}
