// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package apps.inventory.screens;

import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged @SuppressWarnings("unused") aspect ItemDetails2AuditDetailsTable_Aspect {
    
    declare @type: ItemDetails2.AuditDetails : @Component;
	declare @type: ItemDetails2.AuditDetails : @Scope("prototype");
    
	
	
    
    public String ItemDetails2.AuditDetails.getCreatedBy(){
    	return this.createdBy;
    }
    

    public String ItemDetails2.AuditDetails.getCreatedDate(){
    	return this.createdDate;
    }
    

}
