// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.someorg.examples.screens;

import org.openlegacy.terminal.ScreenEntity;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged aspect SignOn_Aspect {
    
    declare @type: SignOn : @Component;
	declare @type: SignOn : @Scope("prototype");
    

    declare parents: SignOn implements ScreenEntity;
    
    

    public String SignOn.getPassword(){
    	return this.password;
    }
    

    public String SignOn.getUser(){
    	return this.user;
    }
    


    
}
