// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.someorg.examples.screens;

import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.ScreenPosition;
import org.openlegacy.terminal.TerminalField;
import org.openlegacy.terminal.TerminalScreen;
import org.openlegacy.terminal.CursorContainer;
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;

privileged aspect SignOn_Aspect {
    
    declare @type: SignOn : @Component;
	declare @type: SignOn : @Scope("prototype");
    
    private TerminalScreen SignOn.terminalScreen;

    declare parents: SignOn implements ScreenEntity;
    declare parents: SignOn implements CursorContainer;

    private ScreenPosition SignOn.cursorPosition;
    
    private TerminalField SignOn.passwordField;
    private TerminalField SignOn.userField;
    
    public TerminalScreen SignOn.getTerminalScreen(){
		return terminalScreen;
    }

    public String SignOn.getPassword(){
    	return this.password;
    }
    

    public TerminalField SignOn.getPasswordField(){
    	return passwordField;
    }
    public String SignOn.getUser(){
    	return this.user;
    }
    

    public TerminalField SignOn.getUserField(){
    	return userField;
    }

    public ScreenPosition SignOn.getCursorPosition(){
    	return cursorPosition;
    }
    public void SignOn.setCursorPosition(ScreenPosition cursorPosition){
    	this.cursorPosition = cursorPosition;
    }
    
}
