// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test1;

import java.util.*;
import org.openlegacy.terminal.ScreenEntity;
import org.openlegacy.terminal.Color;
import org.openlegacy.terminal.definitions.TerminalActionDefinition;

privileged @SuppressWarnings("unused") aspect WarehouseTypes_Aspect {

    declare parents: WarehouseTypes implements ScreenEntity;
    private String WarehouseTypes.focusField;
    private List<TerminalActionDefinition> WarehouseTypes.actions = new ArrayList<TerminalActionDefinition>();
    
	

    

    public List<WarehouseTypesRecord> WarehouseTypes.getWarehouseTypesRecords(){
    	return this.warehouseTypesRecords;
    }
    




    public String WarehouseTypes.getFocusField(){
    	return focusField;
    }
    public void WarehouseTypes.setFocusField(String focusField){
    	this.focusField = focusField;
    }
    
    public List<TerminalActionDefinition> WarehouseTypes.getActions(){
    	return actions;
    }
    
}
