// WARNING: DO NOT EDIT THIS FILE.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openlegacy.recognizers.pattern;

import org.openlegacy.terminal.TerminalField;
import org.openlegacy.terminal.TerminalScreen;
import org.springframework.stereotype.Component;

privileged aspect SignOn_Aspect {
    
    declare @type: SignOn : @Component;
    
    private TerminalScreen SignOn.hostScreen;
    
    private TerminalField SignOn.userField;
    private TerminalField SignOn.passwordField;
    
    public TerminalScreen SignOn.getHostScreen(){
		return hostScreen;
    }
    
    public String SignOn.getUser(){
    	return this.user;
    }
    public void SignOn.setUser(String user){
    	this.user = user;
    }

    public TerminalField SignOn.getUserField(){
    	return userField;
    }

    public String SignOn.getPassword(){
    	return this.password;
    }
    public void SignOn.setPassword(String password){
    	this.password = password;
    }

    public TerminalField SignOn.getPasswordField(){
    	return passwordField;
    }
}
